reddit-on-rails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: %i(new create)
  resources :subs, except: :destroy
  resources :posts, except: :index
  resource :session, only: %i(new create destroy)
end

reddit-on-rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit-on-rails/app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true

  has_many :post_subs, inverse_of: :post, dependent: :destroy

  has_many :subs,
    through: :post_subs,
    source: :sub

  belongs_to :author,
    class_name: :User,
    foreign_key: :author_id,
    inverse_of: :posts
end

reddit-on-rails/app/models/post_sub.rb
class PostSub < ApplicationRecord
  belongs_to :post
  belongs_to :sub
end

reddit-on-rails/app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, presence: true, uniqueness: true

  has_many :post_subs, inverse_of: :sub, dependent: :destroy

  has_many :posts,
    through: :post_subs,
    source: :post

  belongs_to :moderator,
    class_name: :User,
    primary_key: :id,
    foreign_key: :moderator_id,
    inverse_of: :subs
end

reddit-on-rails/app/models/user.rb
class User < ApplicationRecord
  attr_reader :password

  validates :username, :password_digest, :session_token, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many :subs,
    class_name: :Sub,
    foreign_key: :moderator_id,
    inverse_of: :moderator

  has_many :posts,
    class_name: :User,
    foreign_key: :author_id,
    inverse_of: :author

  after_initialize :ensure_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  private

  def ensure_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

end

reddit-on-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login!(user)
    @current_user = user
    session[:session_token] = user.reset_token!
  end

  def logout!
    current_user.try(:reset_token!)
    session[:session_token] = nil
  end

  private

  def require_login
    unless logged_in?
      flash[:errors] = ["You must be logged in to do that"]
      redirect_to new_session_url
    end
  end
end

reddit-on-rails/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, except: :show
  before_action :require_author, only: %i(edit update)

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    @post.author_id = current_user.id

    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content)
  end

  def require_author
    unless Post.find(params[:id]).author == current_user
      flash[:errors] = "You must be the author to make changes"
      redirect_to post_url(@post)
    end
  end
end

reddit-on-rails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user
      login!(user)
      redirect_to subs_url
    else
      flash.now[:errors] = ["Invalid username and password combination"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to subs_url
  end
end

reddit-on-rails/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_login, except: %i(index show)
  before_action :require_moderator, only: %i(edit update)

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])
    @sub.moderator_id = current_user.id

    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def require_moderator
    unless current_user.subs.find(params[:id])
      flash[:errors] = "You must be the sub moderator to make changes"
      redirect_to sub_url(@sub)
    end
  end
end

reddit-on-rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

reddit-on-rails/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input
      type='hidden'
      name='authenticity_token'
      value='#{form_authenticity_token}'>".html_safe
    end
end

reddit-on-rails/app/helpers/posts_helper.rb
module PostsHelper
end

reddit-on-rails/app/helpers/sessions_helper.rb
module SessionsHelper
end

reddit-on-rails/app/helpers/subs_helper.rb
module SubsHelper
end

reddit-on-rails/app/helpers/users_helper.rb
module UsersHelper
end

reddit-on-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditOnRails</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <%= render "shared/error" %>

    <%= yield %>
  </body>
</html>

reddit-on-rails/app/views/posts/edit.html.erb
<section class="form">
  <h1>Edit Post</h1>

  <form action="<%= post_url(@post) %>" method="post">
    <%= auth_token %>
    <input type="hidden" name="_method" value="patch">

    <div class="text_input">
      <label for="post_title">Title</label>
      <input id="post_title" type="text" name="post[title]" value="<%= @post.title %>">
    </div>

    <div class="text_input">
      <label for="post_url">URL</label>
      <input id="post_url" type="text" name="post[url]" value="<%= @post.url %>">
    </div>

    <div class="text_area">
      <label for="post_content">Content</label>
      <textarea id="post_content" name="post[content]" rows="8"  placeholder="Add more details about your post."><%= @post.content %></textarea>
    </div>

    <input type="submit" value="Update Post">
  </form>
</section>

reddit-on-rails/app/views/posts/new.html.erb
<section class="form">
  <h1>Create New Post</h1>

  <form action="<%= posts_url %>" method="post">
    <%= auth_token %>

    <div class="text_input">
      <label for="post_title">Title</label>
      <input id="post_title" type="text" name="post[title]" value="">
    </div>

    <div class="text_input">
      <label for="post_url">URL</label>
      <input id="post_url" type="text" name="post[url]" value="">
    </div>

    <div class="text_area">
      <label for="post_content">Content</label>
      <textarea id="post_content" name="post[content]" rows="8"  placeholder="Add more details about your post."></textarea>
    </div>

    <input type="submit" value="Create Post">
  </form>
</section>

reddit-on-rails/app/views/posts/show.html.erb
<section>
  <%= link_to "Edit Post", edit_post_url(@post) %>

  <h2><%= @post.title %></h2>
  <details open>
    <p>submitted by @<%= @post.author.username %></p>
    <p><%= @post.url %>
    <p><%= @post.content %></p>
  </details>

  <!-- <%# if @post.comments.empty? %>
    <h3>There are no comments yet.</h3>
    <p>Be the first to write something!</p>
  <%# else %>
    <ul class="content-list">
      <%# @post.comments.each do |comment| %>
        <li>
          <p>
            <strong>@<%#= comment.author %>:</strong>
            <%#= comment.content %>
          </p>
        </li>
      <%# end %>
    </ul>
  <%# end %> -->
</section>

reddit-on-rails/app/views/shared/_error.html.erb
<% if flash[:errors] %>
  <section class="errors">
    <ul>
      <% flash[:errors].each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </section>
<% end %>

reddit-on-rails/app/views/shared/_header.html.erb
<header>
  <a href="/subs"><h1><i class="fa fa-reddit" aria-hidden="true"></i> RedditOnRails</h1></a>
  <section class="header-buttons">
    <% if logged_in? %>
      <strong><%= current_user.username %></strong>
      <%= button_to "Sign Out", session_url, method: :delete %>
    <% else %>
      <%= link_to "Sign In", new_session_url %>
      <%= link_to "Sign Up", new_user_url %>
    <% end %>
  </section>
</header>

reddit-on-rails/app/views/subs/edit.html.erb
<section class="form">
  <h1>Edit Sub</h1>

  <form action="<%= sub_url(@sub) %>" method="post">
    <%= auth_token %>
    <input type="hidden" name="_method" value="patch">

    <div class="text_input">
      <label for="sub_title">Title</label>
      <input id="sub_title" type="text" name="sub[title]" value="<%= @sub.title %>">
    </div>

    <div class="text_area">
      <label for="sub_description">Description</label>
      <textarea id="sub_description" name="sub[description]" rows="8"  placeholder="What's your sub about?"><%= @sub.description %></textarea>
    </div>

    <input type="submit" name="" value="Update Sub">
  </form>
</section>

reddit-on-rails/app/views/subs/index.html.erb
<section>
  <%= link_to "Create Sub", new_sub_url %>

  <% if @subs.empty? %>
    <h2>There seems to be nothing here.</h2>
    <p>Why don't you make something new?</p>
  <% else %>
    <h2>Browse Subs</h2>
    <ul class="content-list">
      <% @subs.each do |sub| %>
        <li>
          <h3><%= link_to sub.title, sub_url(sub) %></h3>
          <p><%= sub.description %></p>
        </li>
      <% end %>
    </ul>
  <% end %>
</section>

reddit-on-rails/app/views/subs/new.html.erb
<section class="form">
  <h1>Create New Sub</h1>

  <form action="<%= subs_url %>" method="post">
    <%= auth_token %>

    <div class="text_input">
      <label for="sub_title">Title</label>
      <input id="sub_title" type="text" name="sub[title]" value="">
    </div>

    <div class="text_area">
      <label for="sub_description">Description</label>
      <textarea id="sub_description" name="sub[description]" rows="8"  placeholder="What's your sub about?"></textarea>
    </div>

    <input type="submit" value="Create Sub">
  </form>
</section>

reddit-on-rails/app/views/subs/show.html.erb
<section>
  <%= link_to "Edit Sub", edit_sub_url(@sub) %>
  <%= link_to "Create Post", new_post_url %>

  <h2><%= @sub.title %></h2>
  <details>
    <p>moderated by @<%= @sub.moderator.username %></p>
    <p><%= @sub.description %></p>
  </details>

  <% if @sub.posts.empty? %>
    <h3>There seems to be nothing here.</h3>
    <p>Why don't you make something new?</p>
  <% else %>
    <ul class="content-list">
      <% @sub.posts.each do |post| %>
        <li>
          <h3><%= link_to post.title, post_url(post) %></h3>
          <p>by <%= post.author %></p>
        </li>
      <% end %>
    </ul>
  <% end %>
</section>

reddit-on-rails/app/views/users/new.html.erb
<section class="form">
  <h1>Sign Up</h1>

  <form action="<%= users_url %>" method="post">
    <%= auth_token %>

    <div class="text_input">
      <label for="user_username">Username</label>
      <input id="user_username" type="text" name="user[username]" value="">
    </div>

    <div class="text_input">
      <label for="user_password">Password</label>
      <input id="user_password" type="password" name="user[password]" value="">
    </div>

    <input type="submit" value="Sign Up">
  </form>
</section>